#!/usr/bin/env python3
"""
BIST Stock Name ve Sector Güncelleme Scripti
Database'deki tüm hisselere gerçek isim ve sektör bilgisi ekler
"""

from app import app
from models import db, Stock

# BIST Hisse İsimleri ve Sektörleri
STOCK_DATA = {
    'THYAO': {'name': 'Türk Hava Yolları', 'sector': 'Ulaştırma'},
    'GARAN': {'name': 'Garanti BBVA', 'sector': 'Bankacılık'},
    'AKBNK': {'name': 'Akbank', 'sector': 'Bankacılık'},
    'EREGL': {'name': 'Ereğli Demir Çelik', 'sector': 'Metal Ana'},
    'FROTO': {'name': 'Ford Otosan', 'sector': 'Otomotiv'},
    'ASELS': {'name': 'Aselsan', 'sector': 'Savunma'},
    'MGROS': {'name': 'Migros', 'sector': 'Perakende'},
    'VAKBN': {'name': 'VakıfBank', 'sector': 'Bankacılık'},
    'BIMAS': {'name': 'BİM', 'sector': 'Perakende'},
    'TUPRS': {'name': 'Tüpraş', 'sector': 'Petrol'},
    'KCHOL': {'name': 'Koç Holding', 'sector': 'Holding'},
    'SAHOL': {'name': 'Sabancı Holding', 'sector': 'Holding'},
    'TCELL': {'name': 'Turkcell', 'sector': 'Telekomünikasyon'},
    'ARCLK': {'name': 'Arçelik', 'sector': 'Beyaz Eşya'},
    'KOZAL': {'name': 'Koza Altın', 'sector': 'Madencilik'},
    'PETKM': {'name': 'Petkim', 'sector': 'Petrokimya'},
    'SISE': {'name': 'Şişe Cam', 'sector': 'Cam'},
    'ZOREN': {'name': 'Zorlu Enerji', 'sector': 'Enerji'},
    'ENKAI': {'name': 'Enka İnşaat', 'sector': 'İnşaat'},
    'DOHOL': {'name': 'Doğan Holding', 'sector': 'Holding'},
    'AEFES': {'name': 'Anadolu Efes', 'sector': 'İçecek'},
    'AYGAZ': {'name': 'Aygaz', 'sector': 'Gaz Dağıtım'},
    'BANVT': {'name': 'Banvit', 'sector': 'Gıda'},
    'BEGYO': {'name': 'Batı Gayrimenkul', 'sector': 'GYO'},
    'BFREN': {'name': 'Bosch Fren', 'sector': 'Otomotiv'},
    'BIGCH': {'name': 'Big Chef', 'sector': 'Gıda'},
    'BRISA': {'name': 'Brisa', 'sector': 'Otomotiv'},
    'CCOLA': {'name': 'Coca Cola', 'sector': 'İçecek'},
    'CIMSA': {'name': 'Çimsa', 'sector': 'Çimento'},
    'AKSA': {'name': 'Aksa Enerji', 'sector': 'Enerji'},
    'AKSEN': {'name': 'Aksa Enerji', 'sector': 'Enerji'},
    'ALARK': {'name': 'Alarko Holding', 'sector': 'Holding'},
    'ALBRK': {'name': 'Al Baraka Bank', 'sector': 'Bankacılık'},
    'ALCAR': {'name': 'Alcar', 'sector': 'Otomotiv'},
    'ALCTL': {'name': 'Alcatel', 'sector': 'Telekomünikasyon'},
    'ALFAS': {'name': 'Alfa Solar', 'sector': 'Enerji'},
    'ALGYO': {'name': 'Alarko GYO', 'sector': 'GYO'},
    'ALKA': {'name': 'Alka Kimya', 'sector': 'Kimya'},
    'ALKIM': {'name': 'Alkim Kimya', 'sector': 'Kimya'},
    'ALKLC': {'name': 'Alkim Kağıt', 'sector': 'Kağıt'},
    'ALTNY': {'name': 'Altınyağ', 'sector': 'Gıda'},
    'ANELE': {'name': 'Anele Elektrik', 'sector': 'Elektrik'},
    'ANGEN': {'name': 'Angen Enerji', 'sector': 'Enerji'},
    'ANHYT': {'name': 'Anadolu Hayat', 'sector': 'Sigorta'},
    'ANSGR': {'name': 'Anadolu Sigorta', 'sector': 'Sigorta'},
    'ARENA': {'name': 'Arena Bilgisayar', 'sector': 'Bilişim'},
    'ARMGD': {'name': 'Armada', 'sector': 'Bilişim'},
    'ARSAN': {'name': 'Arsan Tekstil', 'sector': 'Tekstil'},
    'ARTMS': {'name': 'Artemis', 'sector': 'Kimya'},
    'ARZUM': {'name': 'Arzum', 'sector': 'Ev Aletleri'},
    'ASGYO': {'name': 'Aş GYO', 'sector': 'GYO'},
    'ASTOR': {'name': 'Astor Enerji', 'sector': 'Enerji'},
    'ASUZU': {'name': 'Anadolu Isuzu', 'sector': 'Otomotiv'},
    'ATAGY': {'name': 'Ata GYO', 'sector': 'GYO'},
    'ATAKP': {'name': 'Atak Petrol', 'sector': 'Petrol'},
    'ATATP': {'name': 'Atatürk Petrol', 'sector': 'Petrol'},
    'ATEKS': {'name': 'Ateks', 'sector': 'Tekstil'},
    'ATLAS': {'name': 'Atlas', 'sector': 'Tekstil'},
    'AVGYO': {'name': 'Avrasya GYO', 'sector': 'GYO'},
    'AVHOL': {'name': 'Avrupa Holding', 'sector': 'Holding'},
    'AVOD': {'name': 'A.V.O.D.', 'sector': 'Medya'},
    'AVPGY': {'name': 'Avrupay GYO', 'sector': 'GYO'},
    'AVTUR': {'name': 'Avrasya Petrol', 'sector': 'Petrol'},
    'AYCES': {'name': 'Ayçelik', 'sector': 'Metal'},
    'AYDEM': {'name': 'Aydem Enerji', 'sector': 'Enerji'},
    'AYEN': {'name': 'Ayen Enerji', 'sector': 'Enerji'},
    'AYES': {'name': 'Ayes Çelik', 'sector': 'Metal'},
    'AZTEK': {'name': 'Aztek Teknoloji', 'sector': 'Teknoloji'},
    'BAGFS': {'name': 'Bagfaş', 'sector': 'Gıda'},
    'BAHKM': {'name': 'Bahçeşehir Koleji', 'sector': 'Eğitim'},
    'BAKAB': {'name': 'Bakioğlu', 'sector': 'İnşaat'},
    'BALAT': {'name': 'Balataş', 'sector': 'Otomotiv'},
    'BALSU': {'name': 'Balsu', 'sector': 'Su'},
    'BARMA': {'name': 'Barma', 'sector': 'Makine'},
    'BASCM': {'name': 'Başçimento', 'sector': 'Çimento'},
    'BASGZ': {'name': 'Başkent Gaz', 'sector': 'Gaz'},
    'BAYRK': {'name': 'Bayrak Taban', 'sector': 'Tekstil'},
    'BERA': {'name': 'Bera Holding', 'sector': 'Holding'},
    'BESLR': {'name': 'Besler Cement', 'sector': 'Çimento'},
    'BEYAZ': {'name': 'Beyaz Filo', 'sector': 'Taşımacılık'},
    'BIENY': {'name': 'Bio Enerji', 'sector': 'Enerji'},
    'BIGEN': {'name': 'Bigen Genetik', 'sector': 'Biyoteknoloji'},
    'BINBN': {'name': 'Binbinevler', 'sector': 'İnşaat'},
    'BINHO': {'name': 'Bingo', 'sector': 'Perakende'},
    'BIOEN': {'name': 'Bio Enerji', 'sector': 'Enerji'},
    'BIZIM': {'name': 'Bizim Toptan', 'sector': 'Perakende'},
    'BJKAS': {'name': 'Beşiktaş', 'sector': 'Spor'},
    'BLCYT': {'name': 'Bilici Yatırım', 'sector': 'Yatırım'},
    'BMSCH': {'name': 'BMS Çelik', 'sector': 'Metal'},
    'BMSTL': {'name': 'Bermetal', 'sector': 'Metal'},
    'BNTAS': {'name': 'Bantaş', 'sector': 'Otomotiv'},
    'BOBET': {'name': 'Bobet', 'sector': 'İnşaat'},
    'BORLS': {'name': 'Borova', 'sector': 'Orman'},
    'BORSK': {'name': 'Borsaistanbul', 'sector': 'Borsa'},
    'BOSSA': {'name': 'Bossa', 'sector': 'Ticaret'},
    'BRKO': {'name': 'Birko', 'sector': 'Tekstil'},
    'BRKSN': {'name': 'Berkosan', 'sector': 'Kimya'},
    'BRKVY': {'name': 'Berke Vitrifiye', 'sector': 'Seramik'},
    'BRLSM': {'name': 'Birleşim', 'sector': 'Makine'},
    'BRMEN': {'name': 'Birmen', 'sector': 'Tekstil'},
    'BRSAN': {'name': 'Birsan', 'sector': 'Tekstil'},
    'BRYAT': {'name': 'Borusan Yatırım', 'sector': 'Yatırım'},
    'BSOKE': {'name': 'Batısöke', 'sector': 'Çimento'},
    'BTCIM': {'name': 'Batıçim', 'sector': 'Çimento'},
    'BUCIM': {'name': 'Bucim', 'sector': 'Madencilik'},
    'BULGS': {'name': 'Bulgurlu', 'sector': 'Gıda'},
    'BURCE': {'name': 'Burcelik', 'sector': 'Otomotiv'},
    'BURVA': {'name': 'Bursa Çimento', 'sector': 'Çimento'},
    'BVSAN': {'name': 'Bav Sanayi', 'sector': 'Makine'},
    'BYDNR': {'name': 'Beydağı', 'sector': 'Su'},
    'CANTE': {'name': 'Çante', 'sector': 'Deri'},
    'CASA': {'name': 'Casa', 'sector': 'Mobilya'},
    'CATES': {'name': 'Çates', 'sector': 'Elektrik'},
    'CELHA': {'name': 'Çelebi Hava', 'sector': 'Havacılık'},
    'CEMAS': {'name': 'Çemas', 'sector': 'Makine'},
    'CEMTS': {'name': 'Çemtaş', 'sector': 'Çimento'},
    'CEMZY': {'name': 'Çementas', 'sector': 'Çimento'},
    'CEOEM': {'name': 'CEO Event', 'sector': 'Etkinlik'},
    'CGCAM': {'name': 'Çam Cam', 'sector': 'Cam'},
    'CLEBI': {'name': 'Çelebi', 'sector': 'Havacılık'},
    'CMBTN': {'name': 'Çimbeton', 'sector': 'Çimento'},
    'CMENT': {'name': 'Çimentaş', 'sector': 'Çimento'},
    'CONSE': {'name': 'Consus', 'sector': 'İnşaat'},
    'COSMO': {'name': 'Cosmos', 'sector': 'Tekstil'},
    'CRDFA': {'name': 'Credit Europe', 'sector': 'Bankacılık'},
    'CRFSA': {'name': 'Carrefoursa', 'sector': 'Perakende'},
    'CUSAN': {'name': 'Çuhadaroğlu', 'sector': 'Metal'},
    'CVKMD': {'name': 'Çavuşoğlu', 'sector': 'Metal'},
    'CWENE': {'name': 'CW Enerji', 'sector': 'Enerji'},
    'DAGHL': {'name': 'Dağ Holding', 'sector': 'Holding'},
    'DAGI': {'name': 'Dagi', 'sector': 'Tekstil'},
    'DAPGM': {'name': 'DAP Gübre', 'sector': 'Gübre'},
    'DARDL': {'name': 'Dardanel', 'sector': 'Gıda'},
    'DCTTR': {'name': 'Doctor', 'sector': 'Sağlık'},
    'DENGE': {'name': 'Denge', 'sector': 'Holding'},
    'DERHL': {'name': 'Der Holding', 'sector': 'Holding'},
    'DERIM': {'name': 'Derim', 'sector': 'Tekstil'},
    'DESA': {'name': 'Desa', 'sector': 'Deri'},
    'DESPC': {'name': 'Destek', 'sector': 'Bilişim'},
    'DEVA': {'name': 'Deva Holding', 'sector': 'İlaç'},
    'DGATE': {'name': 'Datagate', 'sector': 'Bilişim'},
    'DGGYO': {'name': 'Doğuş GYO', 'sector': 'GYO'},
    'DGNMO': {'name': 'Doğanlar', 'sector': 'Mobilya'},
    'DIRIT': {'name': 'Diriteks', 'sector': 'Tekstil'},
    'DITAS': {'name': 'Ditaş', 'sector': 'Otomotiv'},
    'DMRGD': {'name': 'Demirağ', 'sector': 'İnşaat'},
    'DMSAS': {'name': 'Demisaş', 'sector': 'Demir'},
    'DNISI': {'name': 'Dinsa', 'sector': 'İnşaat'},
    'DOAS': {'name': 'Doğa Sigorta', 'sector': 'Sigorta'},
    'DOBUR': {'name': 'Doburca', 'sector': 'Mining'},
    'DOCO': {'name': 'Doco', 'sector': 'Bilişim'},
    'DOFER': {'name': 'Dofer', 'sector': 'İnşaat'},
    'DOGUB': {'name': 'Doğubank', 'sector': 'Bankacılık'},
    'DOKTA': {'name': 'Dokta', 'sector': 'Sağlık'},
    'DSTKF': {'name': 'Dostekf', 'sector': 'Tekstil'},
    'DURDO': {'name': 'Durdo', 'sector': 'İnşaat'},
    'DURKN': {'name': 'Durukan', 'sector': 'Çimento'},
    'DYOBY': {'name': 'DYO Boya', 'sector': 'Kimya'},
    'DZGYO': {'name': 'Deniz GYO', 'sector': 'GYO'},
    'EBEBK': {'name': 'Egebank', 'sector': 'Bankacılık'},
    'ECILC': {'name': 'Eczacılar', 'sector': 'İlaç'},
    'ECZYT': {'name': 'Eczacıbaşı', 'sector': 'İlaç'},
    'EDATA': {'name': 'E-Data', 'sector': 'Bilişim'},
    'EDIP': {'name': 'Edip İplik', 'sector': 'Tekstil'},
    'EFORC': {'name': 'E-Force', 'sector': 'Bilişim'},
    'EGEEN': {'name': 'Ege Enerji', 'sector': 'Enerji'},
    'EGEGY': {'name': 'Ege GYO', 'sector': 'GYO'},
    'EGEPO': {'name': 'Ege Profil', 'sector': 'Metal'},
    'EGGUB': {'name': 'Ege Gübre', 'sector': 'Gübre'},
    'EGPRO': {'name': 'Ege Profil', 'sector': 'Metal'},
    'EGSER': {'name': 'Ege Seramik', 'sector': 'Seramik'},
    'EKGYO': {'name': 'Emlak Konut GYO', 'sector': 'GYO'},
    'EKIZ': {'name': 'Ekiz', 'sector': 'Kimya'},
    'EKOS': {'name': 'Ekos', 'sector': 'Gıda'},
    'EKSUN': {'name': 'Eksun', 'sector': 'Makine'},
    'ELITE': {'name': 'Elite', 'sector': 'Tekstil'},
    'EMKEL': {'name': 'Emkel', 'sector': 'Elektrik'},
    'EMNIS': {'name': 'Emniyet', 'sector': 'Sigorta'},
    'ENDAE': {'name': 'Endateks', 'sector': 'Tekstil'},
    'ENERY': {'name': 'Enerya', 'sector': 'Enerji'},
    'ENJSA': {'name': 'Enerjisa', 'sector': 'Enerji'},
    'ENSRI': {'name': 'Ensari', 'sector': 'Elektrik'},
    'ENTRA': {'name': 'Entra', 'sector': 'Enerji'},
    'EPLAS': {'name': 'Egeplast', 'sector': 'Plastik'},
    'ERBOS': {'name': 'Erbosan', 'sector': 'Holding'},
    'ERCB': {'name': 'Erciyas', 'sector': 'Çimento'},
    'ERSU': {'name': 'Ersu', 'sector': 'Gıda'},
    'ESCAR': {'name': 'Escar', 'sector': 'Otomotiv'},
    'ESCOM': {'name': 'Escom', 'sector': 'Bilişim'},
    'ESEN': {'name': 'Esen', 'sector': 'Elektrik'},
    'ETILR': {'name': 'Etiler', 'sector': 'Gıda'},
    'ETYAT': {'name': 'Et ve Süt', 'sector': 'Gıda'},
    'EUHOL': {'name': 'Euro Holding', 'sector': 'Holding'},
    'EUKYO': {'name': 'Euro GYO', 'sector': 'GYO'},
    'EUPWR': {'name': 'Euro Power', 'sector': 'Enerji'},
    'EUREN': {'name': 'Euro Enerji', 'sector': 'Enerji'},
    'EUYO': {'name': 'Euro GYO', 'sector': 'GYO'},
    'EYGYO': {'name': 'Ey GYO', 'sector': 'GYO'},
    'FADE': {'name': 'Fade', 'sector': 'Gıda'},
    'FENER': {'name': 'Fenerbahçe', 'sector': 'Spor'},
    'FLAP': {'name': 'Flap', 'sector': 'Gıda'},
    'FMIZP': {'name': 'Fempa', 'sector': 'Plastik'},
    'FONET': {'name': 'Fonet', 'sector': 'Telekomünikasyon'},
    'FORMT': {'name': 'Format', 'sector': 'Medya'},
    'FORTE': {'name': 'Forte', 'sector': 'Teknoloji'},
    'FRIGO': {'name': 'Frigo', 'sector': 'Soğutma'},
    'FZLGY': {'name': 'Fuzul GYO', 'sector': 'GYO'},
    'GARFA': {'name': 'Garanti Faktoring', 'sector': 'Faktoring'},
    'GEDIK': {'name': 'Gedik', 'sector': 'Yatırım'},
    'GEDZA': {'name': 'Gedza', 'sector': 'İlaç'},
    'GENIL': {'name': 'Gentaş', 'sector': 'Tekstil'},
    'GENTS': {'name': 'Genteks', 'sector': 'Tekstil'},
    'GEREL': {'name': 'Gerelit', 'sector': 'Elektrik'},
    'GESAN': {'name': 'Gesan', 'sector': 'Elektrik'},
    'GIPTA': {'name': 'Gıpta', 'sector': 'Kırtasiye'},
    'GLBMD': {'name': 'Global MD', 'sector': 'Sağlık'},
    'GLCVY': {'name': 'Galaksiya', 'sector': 'Bilişim'},
    'GLDTR': {'name': 'Goldtur', 'sector': 'Turizm'},
    'GLRMK': {'name': 'Gülermak', 'sector': 'İnşaat'},
    'GLRYH': {'name': 'Güler', 'sector': 'Yatırım'},
    'GLYHO': {'name': 'Gülyağ', 'sector': 'Gıda'},
    'GMSTR': {'name': 'Gemstar', 'sector': 'Tekstil'},
    'GMTAS': {'name': 'Gemtaş', 'sector': 'İnşaat'},
    'GOKNR': {'name': 'Göknur', 'sector': 'Gıda'},
    'GOLTS': {'name': 'Göltaş', 'sector': 'Çimento'},
    'GOODY': {'name': 'Good Year', 'sector': 'Lastik'},
    'GOZDE': {'name': 'Gözde', 'sector': 'Gıda'},
    'GRNYO': {'name': 'Garanti GYO', 'sector': 'GYO'},
    'GRSEL': {'name': 'Girişim', 'sector': 'Elektrik'},
    'GRTHO': {'name': 'Gürit', 'sector': 'Holding'},
    'GSDDE': {'name': 'GSD Denizcilik', 'sector': 'Denizcilik'},
    'GSDHO': {'name': 'GSD Holding', 'sector': 'Holding'},
    'GSRAY': {'name': 'Galatasaray', 'sector': 'Spor'},
    'GUBRF': {'name': 'Gübre Fabrikaları', 'sector': 'Gübre'},
    'GUNDG': {'name': 'Gündoğdu', 'sector': 'GYO'},
    'GWIND': {'name': 'Galata Wind', 'sector': 'Enerji'},
    'GZNMI': {'name': 'Gaziantep', 'sector': 'Çimento'},
    'HALKB': {'name': 'Halkbank', 'sector': 'Bankacılık'},
    'HALKS': {'name': 'Halk Sigorta', 'sector': 'Sigorta'},
    'HATEK': {'name': 'Hatek', 'sector': 'Tekstil'},
    'HATSN': {'name': 'Hatsan', 'sector': 'Silah'},
    'HDFGS': {'name': 'Hedef Girişim', 'sector': 'Yatırım'},
    'HEDEF': {'name': 'Hedef', 'sector': 'Holding'},
    'HEKTS': {'name': 'Hektaş', 'sector': 'Teknoloji'},
    'HKTM': {'name': 'Hekimoğlu', 'sector': 'Tarım'},
    'HLGYO': {'name': 'Halk GYO', 'sector': 'GYO'},
    'HOROZ': {'name': 'Horoz', 'sector': 'Elektrik'},
    'HRKET': {'name': 'Hareket', 'sector': 'Taşımacılık'},
    'HTTBT': {'name': 'Hit', 'sector': 'Bilişim'},
    'HUBVC': {'name': 'Hub', 'sector': 'Teknoloji'},
    'HUNER': {'name': 'Hüner', 'sector': 'Plastik'},
    'HURGZ': {'name': 'Hurriyet', 'sector': 'Medya'},
    'ICBCT': {'name': 'İçbank', 'sector': 'Bankacılık'},
    'ICUGS': {'name': 'İçucu', 'sector': 'İçecek'},
    'IDGYO': {'name': 'İş GYO', 'sector': 'GYO'},
    'IEYHO': {'name': 'İzey', 'sector': 'Holding'},
    'IHAAS': {'name': 'İhlas', 'sector': 'Medya'},
    'IHEVA': {'name': 'İheva', 'sector': 'İnşaat'},
    'IHGZT': {'name': 'İhlas Gazetecilik', 'sector': 'Medya'},
    'IHLAS': {'name': 'İhlas Holding', 'sector': 'Holding'},
    'IHLGM': {'name': 'İhlas Gayrimenkul', 'sector': 'GYO'},
    'IHYAY': {'name': 'İhlas Yayıncılık', 'sector': 'Medya'},
    'IMASM': {'name': 'İmas', 'sector': 'Makine'},
    'INDES': {'name': 'İndeks', 'sector': 'Bilişim'},
    'INFO': {'name': 'İnfo', 'sector': 'Bilişim'},
    'INGRM': {'name': 'İngram', 'sector': 'Bilişim'},
    'INTEK': {'name': 'İntek', 'sector': 'Teknoloji'},
    'INTEM': {'name': 'İntemiz', 'sector': 'Temizlik'},
    'INVEO': {'name': 'İnveo', 'sector': 'Teknoloji'},
    'INVES': {'name': 'İnvestco', 'sector': 'Yatırım'},
    'IPEKE': {'name': 'İpek', 'sector': 'Tekstil'},
    'ISATR': {'name': 'İş Aatırım', 'sector': 'Yatırım'},
    'ISBIR': {'name': 'İşbir', 'sector': 'Tekstil'},
    'ISBTR': {'name': 'İş Bankası', 'sector': 'Bankacılık'},
    'ISCTR': {'name': 'İş Çelik', 'sector': 'Metal'},
    'ISDMR': {'name': 'İş Demir', 'sector': 'Metal'},
    'ISFIN': {'name': 'İş Finansal', 'sector': 'Finansal'},
    'ISGLK': {'name': 'İş Güvenlik', 'sector': 'Güvenlik'},
    'ISGSY': {'name': 'İş Güvenlik', 'sector': 'Güvenlik'},
    'ISGYO': {'name': 'İş GYO', 'sector': 'GYO'},
    'ISIST': {'name': 'İsyst', 'sector': 'Bilişim'},
    'ISKPL': {'name': 'İskenderun', 'sector': 'Çimento'},
    'ISKUR': {'name': 'İş Kur', 'sector': 'Finansal'},
    'ISMEN': {'name': 'İşmen', 'sector': 'Tekstil'},
    'ISSEN': {'name': 'İşsen', 'sector': 'Çelik'},
    'ISYAT': {'name': 'İş Yatırım', 'sector': 'Yatırım'},
    'IZENR': {'name': 'İzen', 'sector': 'Enerji'},
    'IZFAS': {'name': 'İzfaş', 'sector': 'Tekstil'},
    'IZINV': {'name': 'İz Yatırım', 'sector': 'Yatırım'},
    'IZMDC': {'name': 'İzmit', 'sector': 'Çimento'},
    'JANTS': {'name': 'Jant', 'sector': 'Otomotiv'},
    'KAPLM': {'name': 'Kaplamin', 'sector': 'Kimya'},
    'KAREL': {'name': 'Karel', 'sector': 'Telekomünikasyon'},
    'KARSN': {'name': 'Karsan', 'sector': 'Otomotiv'},
    'KARTN': {'name': 'Karton', 'sector': 'Kağıt'},
    'KATMR': {'name': 'Katmerciler', 'sector': 'Otomotiv'},
    'KAYSE': {'name': 'Kayseri', 'sector': 'Şeker'},
    'KBORU': {'name': 'Korkmaz', 'sector': 'Metal'},
    'KCAER': {'name': 'Kocaer', 'sector': 'Havacılık'},
    'KENT': {'name': 'Kent Gıda', 'sector': 'Gıda'},
    'KERVN': {'name': 'Kervan', 'sector': 'Gıda'},
    'KFEIN': {'name': 'Kafein', 'sector': 'Yazılım'},
    'KGYO': {'name': 'Koç GYO', 'sector': 'GYO'},
    'KIMMR': {'name': 'Kimteks', 'sector': 'Kimya'},
    'KLGYO': {'name': 'Kiler GYO', 'sector': 'GYO'},
    'KLKIM': {'name': 'Kalekim', 'sector': 'Kimya'},
    'KLMSN': {'name': 'Klimasan', 'sector': 'Klimatik'},
    'KLNMA': {'name': 'Kaleceramik', 'sector': 'Seramik'},
    'KLRHO': {'name': 'Kiler Holding', 'sector': 'Holding'},
    'KLSER': {'name': 'Kaleseramik', 'sector': 'Seramik'},
    'KLSYN': {'name': 'Kaleseramik', 'sector': 'Seramik'},
    'KLYPV': {'name': 'Kale Yapı', 'sector': 'İnşaat'},
    'KMPUR': {'name': 'Kampür', 'sector': 'Otomotiv'},
    'KNFRT': {'name': 'Konfort', 'sector': 'Mobilya'},
    'KOCMT': {'name': 'Kocametal', 'sector': 'Metal'},
    'KONKA': {'name': 'Konka', 'sector': 'Elektronik'},
    'KONTR': {'name': 'Kontrolmatik', 'sector': 'Otomasyon'},
    'KONYA': {'name': 'Konya Çimento', 'sector': 'Çimento'},
    'KOPOL': {'name': 'Koza Polyester', 'sector': 'Tekstil'},
    'KORDS': {'name': 'Kordsa', 'sector': 'Kimya'},
    'KOTON': {'name': 'Koton', 'sector': 'Tekstil'},
    'KOZAA': {'name': 'Koza Anadolu', 'sector': 'Madencilik'},
    'KRDMA': {'name': 'Kardemir A', 'sector': 'Metal'},
    'KRDMB': {'name': 'Kardemir B', 'sector': 'Metal'},
    'KRDMD': {'name': 'Kardemir D', 'sector': 'Metal'},
    'KRGYO': {'name': 'Kren GYO', 'sector': 'GYO'},
    'KRONT': {'name': 'Kron', 'sector': 'Teknoloji'},
    'KRPLS': {'name': 'Körfez', 'sector': 'Ulaştırma'},
    'KRSTL': {'name': 'Kristal', 'sector': 'Soda'},
    'KRTEK': {'name': 'Kartek', 'sector': 'Kağıt'},
    'KRVGD': {'name': 'Kervangıda', 'sector': 'Gıda'},
    'KSTUR': {'name': 'Kestur', 'sector': 'Turizm'},
    'KTLEV': {'name': 'Katılım', 'sector': 'Bankacılık'},
    'KTSKR': {'name': 'Kütahya', 'sector': 'Şeker'},
    'KUTPO': {'name': 'Kutlar', 'sector': 'Otomotiv'},
    'KUVVA': {'name': 'Kuvva', 'sector': 'Enerji'},
    'KUYAS': {'name': 'Kuyaş', 'sector': 'Enerji'},
    'KZBGY': {'name': 'Kuzey GYO', 'sector': 'GYO'},
    'KZGYO': {'name': 'Kazancı GYO', 'sector': 'GYO'},
    'LIDER': {'name': 'Lider', 'sector': 'Faktoring'},
    'LIDFA': {'name': 'Lider Faktoring', 'sector': 'Faktoring'},
    'LILAK': {'name': 'Lilak', 'sector': 'Gıda'},
    'LINK': {'name': 'Link', 'sector': 'Bilişim'},
    'LKMNH': {'name': 'Lokman', 'sector': 'Sağlık'},
    'LMKDC': {'name': 'Limak', 'sector': 'İnşaat'},
    'LOGO': {'name': 'Logo', 'sector': 'Yazılım'},
    'LRSHO': {'name': 'Lers', 'sector': 'Holding'},
    'LUKSK': {'name': 'Luks', 'sector': 'Kadayıf'},
    'LYDHO': {'name': 'Lydian', 'sector': 'Holding'},
    'LYDYE': {'name': 'Lydian', 'sector': 'Enerji'},
    'MAALT': {'name': 'Mapa', 'sector': 'İnşaat'},
    'MACKO': {'name': 'Mackolik', 'sector': 'Medya'},
    'MAGEN': {'name': 'Magen', 'sector': 'Enerji'},
    'MAKIM': {'name': 'Makine', 'sector': 'Makine'},
    'MAKTK': {'name': 'Maktek', 'sector': 'Teknoloji'},
    'MANAS': {'name': 'Manas', 'sector': 'Enerji'},
    'MARBL': {'name': 'Marble', 'sector': 'Mermer'},
    'MARKA': {'name': 'Marka', 'sector': 'Yatırım'},
    'MARTI': {'name': 'Martı', 'sector': 'Turizm'},
    'MAVI': {'name': 'Mavi', 'sector': 'Tekstil'},
    'MEDTR': {'name': 'Mediter', 'sector': 'Sağlık'},
    'MEGAP': {'name': 'Mega', 'sector': 'Polimer'},
    'MEGMT': {'name': 'Mega', 'sector': 'Metal'},
    'MEKAG': {'name': 'Meka', 'sector': 'Makine'},
    'MEPET': {'name': 'Mepet', 'sector': 'Petrol'},
    'MERCN': {'name': 'Mercan', 'sector': 'Kimya'},
    'MERIT': {'name': 'Merit', 'sector': 'Turizm'},
    'MERKO': {'name': 'Merko', 'sector': 'İnşaat'},
    'METRO': {'name': 'Metro', 'sector': 'Perakende'},
    'METUR': {'name': 'Metur', 'sector': 'Turizm'},
    'MHRGY': {'name': 'Mahram GYO', 'sector': 'GYO'},
    'MIATK': {'name': 'MİA', 'sector': 'Teknoloji'},
    'MMCAS': {'name': 'MMC', 'sector': 'Teknoloji'},
    'MNDRS': {'name': 'Menderes', 'sector': 'Tekstil'},
    'MNDTR': {'name': 'Menderes', 'sector': 'Turizm'},
    'MOBTL': {'name': 'Mobitel', 'sector': 'Telekomünikasyon'},
    'MOGAN': {'name': 'Mogan', 'sector': 'Enerji'},
    'MOPAS': {'name': 'Mopas', 'sector': 'Otomotiv'},
    'MPARK': {'name': 'Mpark', 'sector': 'Teknoloji'},
    'MRGYO': {'name': 'Marti GYO', 'sector': 'GYO'},
    'MRSHL': {'name': 'Marshall', 'sector': 'Perakende'},
    'MSGYO': {'name': 'Mistral GYO', 'sector': 'GYO'},
    'MTRKS': {'name': 'Matriks', 'sector': 'Bilişim'},
    'MTRYO': {'name': 'Metro GYO', 'sector': 'GYO'},
    'MZHLD': {'name': 'Mazhar', 'sector': 'Holding'},
    'NATEN': {'name': 'Naturel', 'sector': 'Enerji'},
    'NETAS': {'name': 'Netaş', 'sector': 'Telekomünikasyon'},
    'NIBAS': {'name': 'Nihat', 'sector': 'Tekstil'},
    'NTGAZ': {'name': 'Naturel Gaz', 'sector': 'Gaz'},
    'NTHOL': {'name': 'Net Holding', 'sector': 'Holding'},
    'NUGYO': {'name': 'Nurol GYO', 'sector': 'GYO'},
    'NUHCM': {'name': 'Nuh Çimento', 'sector': 'Çimento'},
    'OBAMS': {'name': 'Obama', 'sector': 'Bilişim'},
    'OBASE': {'name': 'Obase', 'sector': 'Teknoloji'},
    'ODAS': {'name': 'Odas', 'sector': 'Elektrik'},
    'ODINE': {'name': 'Odin', 'sector': 'Enerji'},
    'OFSYM': {'name': 'Ofis', 'sector': 'Kırtasiye'},
    'ONCSM': {'name': 'Oncosem', 'sector': 'Sağlık'},
    'ONRYT': {'name': 'Onur', 'sector': 'Yatırım'},
    'OPTGY': {'name': 'Optima GYO', 'sector': 'GYO'},
    'OPTLR': {'name': 'Optimar', 'sector': 'Gıda'},
    'ORCAY': {'name': 'Orcay', 'sector': 'Gıda'},
    'ORGE': {'name': 'Örge', 'sector': 'Enerji'},
    'ORMA': {'name': 'Orma', 'sector': 'Orman'},
    'OSMEN': {'name': 'Osmanlı', 'sector': 'Bankacılık'},
    'OSTIM': {'name': 'Ostim', 'sector': 'Sanayi'},
    'OTKAR': {'name': 'Otokar', 'sector': 'Otomotiv'},
    'OTTO': {'name': 'Otto', 'sector': 'Sanayi'},
    'OYAKC': {'name': 'Oyak Çimento', 'sector': 'Çimento'},
    'OYAYO': {'name': 'Oyak GYO', 'sector': 'GYO'},
    'OYLUM': {'name': 'Oylum', 'sector': 'Gıda'},
    'OYYAT': {'name': 'Oyak Yatırım', 'sector': 'Yatırım'},
    'OZATD': {'name': 'Özata', 'sector': 'Tekstil'},
    'OZGYO': {'name': 'Özak GYO', 'sector': 'GYO'},
    'OZKGY': {'name': 'Özak GYO', 'sector': 'GYO'},
    'OZRDN': {'name': 'Özrende', 'sector': 'Gıda'},
    'OZSUB': {'name': 'Özsu', 'sector': 'Su'},
    'OZYSR': {'name': 'Özyeğin', 'sector': 'Yatırım'},
    'PAGYO': {'name': 'Panora GYO', 'sector': 'GYO'},
    'PAMEL': {'name': 'Pamel', 'sector': 'Enerji'},
    'PAPIL': {'name': 'Papilion', 'sector': 'Holding'},
    'PARSN': {'name': 'Parsan', 'sector': 'Makine'},
    'PASEU': {'name': 'Pasifik', 'sector': 'Yatırım'},
    'PATEK': {'name': 'Patek', 'sector': 'Tekstil'},
    'PCILT': {'name': 'Pimaş', 'sector': 'Plastik'},
    'PEKGY': {'name': 'Peker GYO', 'sector': 'GYO'},
    'PENGD': {'name': 'Penguen', 'sector': 'Gıda'},
    'PENTA': {'name': 'Penta', 'sector': 'Teknoloji'},
    'PETUN': {'name': 'Petün', 'sector': 'Tarım'},
    'PGSUS': {'name': 'Pegasus', 'sector': 'Havacılık'},
    'PINSU': {'name': 'Pınar Su', 'sector': 'İçecek'},
    'PKART': {'name': 'Pınar Karton', 'sector': 'Kağıt'},
    'PKENT': {'name': 'Pınar Kent', 'sector': 'GYO'},
    'PLTUR': {'name': 'Plato', 'sector': 'Turizm'},
    'PNLSN': {'name': 'Panelsan', 'sector': 'İnşaat'},
    'PNSUT': {'name': 'Pınar Süt', 'sector': 'Gıda'},
    'POLHO': {'name': 'Polisan', 'sector': 'Kimya'},
    'POLTK': {'name': 'Politeknik', 'sector': 'Metal'},
    'PRDGS': {'name': 'Pardus', 'sector': 'Teknoloji'},
    'PRKAB': {'name': 'Park', 'sector': 'Elektrik'},
    'PRKME': {'name': 'Park', 'sector': 'Makine'},
    'PRZMA': {'name': 'Prizma', 'sector': 'GYO'},
    'PSDTC': {'name': 'Pronet', 'sector': 'Güvenlik'},
    'PSGYO': {'name': 'Paşabahçe GYO', 'sector': 'GYO'},
    'QNBFK': {'name': 'QNB Finansbank', 'sector': 'Bankacılık'},
    'QNBTR': {'name': 'QNB Turkey', 'sector': 'Bankacılık'},
    'QTEMZ': {'name': 'Q Temizlik', 'sector': 'Temizlik'},
    'QUAGR': {'name': 'Qua', 'sector': 'GYO'},
    'RALYH': {'name': 'Rally', 'sector': 'Yatırım'},
    'RAYSG': {'name': 'Ray Sigorta', 'sector': 'Sigorta'},
    'REEDR': {'name': 'Reeder', 'sector': 'Teknoloji'},
    'RGYAS': {'name': 'Reysaş', 'sector': 'Taşımacılık'},
    'RNPOL': {'name': 'Renault', 'sector': 'Otomotiv'},
    'RODRG': {'name': 'Rodrigo', 'sector': 'Tekstil'},
    'ROYAL': {'name': 'Royal', 'sector': 'Halkla İlişkiler'},
    'RTALB': {'name': 'RTA', 'sector': 'Laboratuvar'},
    'RUBNS': {'name': 'Rubenis', 'sector': 'Gıda'},
    'RUZYE': {'name': 'Rüzgar', 'sector': 'Enerji'},
    'RYGYO': {'name': 'Reysaş GYO', 'sector': 'GYO'},
    'RYSAS': {'name': 'Reysaş', 'sector': 'Lojistik'},
    'SAFKR': {'name': 'Safkar', 'sector': 'Enerji'},
    'SAMAT': {'name': 'Samat', 'sector': 'Kağıt'},
    'SANEL': {'name': 'Sanel', 'sector': 'Elektrik'},
    'SANFM': {'name': 'Sanfarm', 'sector': 'İlaç'},
    'SANKO': {'name': 'Sanko', 'sector': 'Tekstil'},
    'SARKY': {'name': 'Sarkuysan', 'sector': 'Metal'},
    'SASA': {'name': 'Sasa', 'sector': 'Kimya'},
    'SAYAS': {'name': 'Saraylar', 'sector': 'GYO'},
    'SDTTR': {'name': 'Soda', 'sector': 'Kimya'},
    'SEGMN': {'name': 'Segment', 'sector': 'Bilişim'},
    'SEGYO': {'name': 'Ses GYO', 'sector': 'GYO'},
    'SEKFK': {'name': 'Şeker', 'sector': 'Faktoring'},
    'SEKUR': {'name': 'Sekuro', 'sector': 'Plastik'},
    'SELEC': {'name': 'Selec', 'sector': 'Teknoloji'},
    'SELGD': {'name': 'Selçuk', 'sector': 'Gıda'},
    'SELVA': {'name': 'Selva', 'sector': 'Gıda'},
    'SERNT': {'name': 'Seren', 'sector': 'Teknoloji'},
    'SEYKM': {'name': 'Seyitömer', 'sector': 'Kimya'},
    'SILVR': {'name': 'Silver', 'sector': 'Teknoloji'},
    'SKBNK': {'name': 'Şeker Bank', 'sector': 'Bankacılık'},
    'SKTAS': {'name': 'Sektaş', 'sector': 'Metal'},
    'SKYLP': {'name': 'Sky', 'sector': 'Havacılık'},
    'SKYMD': {'name': 'Sky', 'sector': 'Medya'},
    'SMART': {'name': 'Smart', 'sector': 'Teknoloji'},
    'SMRTG': {'name': 'Smart', 'sector': 'GYO'},
    'SMRVA': {'name': 'Samer', 'sector': 'Tarım'},
    'SNGYO': {'name': 'Sinpaş GYO', 'sector': 'GYO'},
    'SNICA': {'name': 'Senkron', 'sector': 'Teknoloji'},
    'SNKRN': {'name': 'Şen', 'sector': 'Kırtasiye'},
    'SNPAM': {'name': 'Sinpaş', 'sector': 'İnşaat'},
    'SODSN': {'name': 'Soda Sanayi', 'sector': 'Kimya'},
    'SOKE': {'name': 'Söke', 'sector': 'Çimento'},
    'SOKM': {'name': 'Şok', 'sector': 'Perakende'},
    'SONME': {'name': 'Sönmez', 'sector': 'Tekstil'},
    'SRVGY': {'name': 'Servet GYO', 'sector': 'GYO'},
    'SUMAS': {'name': 'Sumaş', 'sector': 'Makine'},
    'SUNTK': {'name': 'Suntek', 'sector': 'Teknoloji'},
    'SURGY': {'name': 'Sur GYO', 'sector': 'GYO'},
    'SUWEN': {'name': 'Suwen', 'sector': 'Tekstil'},
    'TABGD': {'name': 'Tabgıda', 'sector': 'Gıda'},
    'TARKM': {'name': 'Tarkem', 'sector': 'Kimya'},
    'TATEN': {'name': 'Tat', 'sector': 'Gıda'},
    'TATGD': {'name': 'Tat Gıda', 'sector': 'Gıda'},
    'TAVHL': {'name': 'TAV', 'sector': 'Havacılık'},
    'TBORG': {'name': 'Tuborg', 'sector': 'İçecek'},
    'TCKRC': {'name': 'Türk Kızılay', 'sector': 'Sağlık'},
    'TDGYO': {'name': 'Torunlar GYO', 'sector': 'GYO'},
    'TEHOL': {'name': 'Teknosa', 'sector': 'Perakende'},
    'TEKTU': {'name': 'Tek-Art', 'sector': 'Teknoloji'},
    'TERA': {'name': 'Tera', 'sector': 'Yatırım'},
    'TEZOL': {'name': 'Tezol', 'sector': 'Kimya'},
    'TGSAS': {'name': 'Tügsaş', 'sector': 'Otomotiv'},
    'TKFEN': {'name': 'Tekfen', 'sector': 'İnşaat'},
    'TKNSA': {'name': 'Teknosa', 'sector': 'Perakende'},
    'TLMAN': {'name': 'Talman', 'sector': 'Makine'},
    'TMPOL': {'name': 'Temapol', 'sector': 'Polimer'},
    'TMSN': {'name': 'Tümosan', 'sector': 'Makine'},
    'TNZTP': {'name': 'Tenzile', 'sector': 'Tekstil'},
    'TOASO': {'name': 'Tofaş', 'sector': 'Otomotiv'},
    'TRCAS': {'name': 'Turcas', 'sector': 'Enerji'},
    'TRGYO': {'name': 'Torunlar GYO', 'sector': 'GYO'},
    'TRILC': {'name': 'Trilye', 'sector': 'Çimento'},
    'TSGYO': {'name': 'Tskb GYO', 'sector': 'GYO'},
    'TSKB': {'name': 'TSKB', 'sector': 'Bankacılık'},
    'TSPOR': {'name': 'Trabzonspor', 'sector': 'Spor'},
    'TTKOM': {'name': 'Türk Telekom', 'sector': 'Telekomünikasyon'},
    'TTRAK': {'name': 'Türk Traktör', 'sector': 'Makine'},
    'TUCLK': {'name': 'Tuğ', 'sector': 'Çelik'},
    'TUKAS': {'name': 'Tukaş', 'sector': 'Gıda'},
    'TUREX': {'name': 'Turex', 'sector': 'Turizm'},
    'TURGG': {'name': 'Türkiye Garanti', 'sector': 'Bankacılık'},
    'TURSG': {'name': 'Turcas', 'sector': 'Sigorta'},
    'UFUK': {'name': 'Ufuk', 'sector': 'Yatırım'},
    'ULAS': {'name': 'Ulaş', 'sector': 'Taşımacılık'},
    'ULKER': {'name': 'Ülker', 'sector': 'Gıda'},
    'ULUFA': {'name': 'Ulusal', 'sector': 'Faktoring'},
    'ULUSE': {'name': 'Ulusoy', 'sector': 'Elektrik'},
    'ULUUN': {'name': 'Uluönder', 'sector': 'Un'},
    'UMPAS': {'name': 'Ümpaş', 'sector': 'Tekstil'},
    'UNLU': {'name': 'Ünlü', 'sector': 'Yatırım'},
    'USAK': {'name': 'Uşak', 'sector': 'Seramik'},
    'USDTR': {'name': 'USD', 'sector': 'Teknoloji'},
    'VAKFN': {'name': 'Vakıf Finansal', 'sector': 'Finansal'},
    'VAKKO': {'name': 'Vakko', 'sector': 'Tekstil'},
    'VANGD': {'name': 'Van Gıda', 'sector': 'Gıda'},
    'VBTYZ': {'name': 'VBT', 'sector': 'Yatırım'},
    'VERTU': {'name': 'Vertu', 'sector': 'Turizm'},
    'VERUS': {'name': 'Verus', 'sector': 'Yatırım'},
    'VESBE': {'name': 'Vestel Beyaz', 'sector': 'Beyaz Eşya'},
    'VESTL': {'name': 'Vestel', 'sector': 'Elektronik'},
    'VKFYO': {'name': 'Vakıf GYO', 'sector': 'GYO'},
    'VKGYO': {'name': 'Vakıf GYO', 'sector': 'GYO'},
    'VKING': {'name': 'Viking', 'sector': 'Kağıt'},
    'VRGYO': {'name': 'Verusa GYO', 'sector': 'GYO'},
    'VSNMD': {'name': 'Vestel', 'sector': 'Medya'},
    'YAPRK': {'name': 'Yaprak', 'sector': 'Süt'},
    'YATAS': {'name': 'Yataş', 'sector': 'Yatak'},
    'YAYLA': {'name': 'Yayla', 'sector': 'Enerji'},
    'YBTAS': {'name': 'Yıldız', 'sector': 'Entegre'},
    'YEOTK': {'name': 'Yeşil', 'sector': 'Otomotiv'},
    'YESIL': {'name': 'Yeşil', 'sector': 'Gıda'},
    'YGGYO': {'name': 'Yapı Kredi GYO', 'sector': 'GYO'},
    'YGYO': {'name': 'Yapı GYO', 'sector': 'GYO'},
    'YIGIT': {'name': 'Yiğit', 'sector': 'Kimya'},
    'YKBNK': {'name': 'Yapı Kredi', 'sector': 'Bankacılık'},
    'YKSLN': {'name': 'Yüksel', 'sector': 'İnşaat'},
    'YONGA': {'name': 'Yonga', 'sector': 'Orman'},
    'YUNSA': {'name': 'Yunsa', 'sector': 'Tekstil'},
    'YYAPI': {'name': 'Yeni Yapı', 'sector': 'İnşaat'},
    'YYLGD': {'name': 'Yayla Gıda', 'sector': 'Gıda'},
    'ZEDUR': {'name': 'Zedur', 'sector': 'Enerji'},
    'ZELOT': {'name': 'Zelot', 'sector': 'Teknoloji'},
    'ZGOLD': {'name': 'Ziraat', 'sector': 'Altın'},
}

def update_stock_names():
    """Stock isimlerini güncelle"""
    print("🔄 Stock isimleri güncelleniyor...")
    
    with app.app_context():
        updated_count = 0
        
        for symbol, info in STOCK_DATA.items():
            stock = Stock.query.filter_by(symbol=symbol).first()
            if stock:
                stock.name = info['name']
                stock.sector = info['sector']
                updated_count += 1
                print(f"✅ {symbol}: {info['name']} ({info['sector']})")
        
        # Changes'leri kaydet
        db.session.commit()
        print(f"\n🎯 Toplam {updated_count} hisse güncellendi!")

if __name__ == '__main__':
    update_stock_names()
